apiVersion: apps/v1
kind: Deployment
metadata:
  name: help
  labels:
    app: help
spec:
  replicas: 1
  selector:
    matchLabels:
      app: help
  template:
    metadata:
      labels:
        app: help
    spec:
      containers:
        - name: help
          image: username/help:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5